MICROVERSE: Form
shahnaeem/microverse-form pull request #3
Opened 2020-09-27 18:12 UTC by anapdh

2020-09-28 14:45 UTC, anapdh commented
The features created on this branch were:

- A "Sign In" button, that when clicked directs to the login page;
- The logo of the Company displayed right above the main content;
- The main content as an input form to create an account for the website;
- The form uses email, phone, and a password as the values of its inputs;
- Clickable anchor links, but with no value.

2020-09-28 21:37 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__This is an awesome project :muscle:__
- All linter checks are green :green_circle: 
- Nice Readme :+1: 
- Proper use of HTML semantic tags :ok_hand: 

__However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

_This review will be based on the fact that you are expected to make the appearance of your page matches the mint's sign up page._



- [ ] Your pull request description should be exactly inside the description area, and should not be a comment. It should be the next thing immediately after your PR title.
- Kindly move your PR description to its right place. To do that, See the image below. Click on the `. . .` where the arrow is pointing to and select `Edit`. 

![22:06:57](https://user-images.githubusercontent.com/26856491/94486941-0d24a080-01d8-11eb-8d17-3bce620d9d1b.png)

- [ ] The `fa-lock` icons inside the two buttons should be the same color (white)  as the text inside the buttons. Kindly fix this.

Source Page:
![22:19:49](https://user-images.githubusercontent.com/26856491/94487499-08142100-01d9-11eb-998c-49a70e354b87.png)

Your Page:
![22:20:10](https://user-images.githubusercontent.com/26856491/94487509-0ba7a800-01d9-11eb-9a63-59c142e1cefb.png)

- [ ] Change the border color of your input boxes to match that of the original page.

- [ ] Observe closely the margins, white spaces, and padding of all the elements in the source page and try to use them to adjust your page. See the image below.

Source page:
![22:31:07](https://user-images.githubusercontent.com/26856491/94488480-963cd700-01da-11eb-9264-6f6abb174fa0.png)

Your page:
![22:32:55](https://user-images.githubusercontent.com/26856491/94488488-9a68f480-01da-11eb-8f03-a2ca7b3f98b9.png)



**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-09-28 21:37 UTC, teekaytech commented on index.html
> +          <input class="phoneform input-size" id="phoneform" type="number" name="phone">
The `Phone Number` field should be of `type="tel"`, and not `type="number"`. Kindly change the type of input.

![22:27:56](https://user-images.githubusercontent.com/26856491/94488073-e2d3e280-01d9-11eb-823b-b61f59f80062.png)

2020-09-29 01:51 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great effort!!

### [Mandatory] :red_circle: 

- [ ] MIT license does not correspond to the project. See comments

- [ ] Product logos does not match the original order.
![image](https://user-images.githubusercontent.com/25774518/94502453-ccbe2600-01c9-11eb-8d80-58302b276230.png)

- [ ] Project HTML is missing ```<body>``` tag. See comments

- [ ] ```<input>``` should be outside the ```<label>``` tag. example:
```
  ...
  <label for="male">Male</label>
  <input type="radio" name="gender" id="male" value="male"><br>
  <label for="male">Male</label>
  <input type="radio" name="gender" id="male" value="male"><br>
  ...
```

### [OPTIONAL] :large_blue_circle: 

- [ ] For future projects choose a meaningful branch name. Example:
**Actual**: ```form```
**Improved** :+1: : ```mint-signup-form```
This helps readability and helps the reader and the programmer understand the intent of the branch.

### [Comments] :green_circle: 

Is Great that you added a license to your project. Is a great habit and best practice. Please follow the next steps to create your own version of the MIT license.
- [ ] Create a copy of the license you're using and add it to the project repository in a ```license.md``` file
- [ ] Update it with the name(s) of the owners of the project.
![image](https://user-images.githubusercontent.com/25774518/94501882-6f75a500-01c8-11eb-8934-4d9c8a1ed1ae.png)
- [ ] Update the License link in the README 

The ```<body>``` tag is an important part of the HTML file structure; is the one that defines the document's body, and contains all the contents of an HTML document, such as headings, paragraphs, images, hyperlinks, tables, lists, etc. 

If you notice, the page still renders as intended, this is because the browsers are kind of smart and try to interpret the code as best as possible. This will not always be the case, so its important to maintain the HTML structure as it has to be. 

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-29 16:47 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

You did an amazing job in fixing all the changes required by the last reviewer, keep up the good work :muscle: 
Good luck with your next project.

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

2020-09-29 16:51 UTC, merged